/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CombinedAnalysisRouteImport } from './routes/combined-analysis'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ImageAnalysisRouteImport } from './routes/image-analysis'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WaterAnalysisRouteImport } from './routes/water-analysis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CombinedAnalysisRoute = CombinedAnalysisRouteImport.update({
  id: '/combined-analysis',
  path: '/combined-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageAnalysisRoute = ImageAnalysisRouteImport.update({
  id: '/image-analysis',
  path: '/image-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterAnalysisRoute = WaterAnalysisRouteImport.update({
  id: '/water-analysis',
  path: '/water-analysis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/combined-analysis': typeof CombinedAnalysisRoute
  '/history': typeof HistoryRoute
  '/image-analysis': typeof ImageAnalysisRoute
  '/recommendations': typeof RecommendationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/water-analysis': typeof WaterAnalysisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/combined-analysis': typeof CombinedAnalysisRoute
  '/history': typeof HistoryRoute
  '/image-analysis': typeof ImageAnalysisRoute
  '/recommendations': typeof RecommendationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/water-analysis': typeof WaterAnalysisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/combined-analysis': typeof CombinedAnalysisRoute
  '/history': typeof HistoryRoute
  '/image-analysis': typeof ImageAnalysisRoute
  '/recommendations': typeof RecommendationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/water-analysis': typeof WaterAnalysisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/combined-analysis'
    | '/history'
    | '/image-analysis'
    | '/recommendations'
    | '/reports'
    | '/settings'
    | '/water-analysis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/combined-analysis'
    | '/history'
    | '/image-analysis'
    | '/recommendations'
    | '/reports'
    | '/settings'
    | '/water-analysis'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analytics'
    | '/combined-analysis'
    | '/history'
    | '/image-analysis'
    | '/recommendations'
    | '/reports'
    | '/settings'
    | '/water-analysis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CombinedAnalysisRoute: typeof CombinedAnalysisRoute
  HistoryRoute: typeof HistoryRoute
  ImageAnalysisRoute: typeof ImageAnalysisRoute
  RecommendationsRoute: typeof RecommendationsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  WaterAnalysisRoute: typeof WaterAnalysisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combined-analysis': {
      id: '/combined-analysis'
      path: '/combined-analysis'
      fullPath: '/combined-analysis'
      preLoaderRoute: typeof CombinedAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-analysis': {
      id: '/image-analysis'
      path: '/image-analysis'
      fullPath: '/image-analysis'
      preLoaderRoute: typeof ImageAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water-analysis': {
      id: '/water-analysis'
      path: '/water-analysis'
      fullPath: '/water-analysis'
      preLoaderRoute: typeof WaterAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyticsRoute: AnalyticsRoute,
  CombinedAnalysisRoute: CombinedAnalysisRoute,
  HistoryRoute: HistoryRoute,
  ImageAnalysisRoute: ImageAnalysisRoute,
  RecommendationsRoute: RecommendationsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  WaterAnalysisRoute: WaterAnalysisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
